### ISSUE TITLE
example no longer working

### ISSUE THREAD

**Issue by Dschoni** [nschloe/quadpy#101]
I only checked this for quadrilateral as it's the only one I use, but probably needs adjustment in other examples as well:

```
val = quadpy.quadrilateral.integrate(
    lambda x: numpy.exp(x[0]),
    quadpy.quadrilateral.rectangle_points([0.0, 1.0], [-0.3, 0.6]),
    quadpy.quadrilateral.Stroud(6)
    )
```

in the readme does no longer work as the indices refer to the indices in Stoud's publication (such as `'C2 7-3'`). Furthermore an explanation of index ordering would be nice, as this changed from the old versions of this package.

Like in: "Rectangle points are now given in `[x0,x1][y0,y1]` order" (If I assume correctly)
In old versions it was `[[x0,y0][x1,y1][x2,y2][x3,y3]]`; this might be confusing. At least for me it was.

**Comment by nschloe** [comment]
Thanks for the report! I'll check it out later.

The point specification has changed indeed; it's now an array of shape `(2, 2, whatever)`, where `arr[0][0]` is the "lower left" corner, `arr[1][1]` the "upper right". Same with hexahedra, or n-cubes by the way. (Adding n-cubes had me realize that no order of corner points is as natural as this.)

Anyhow,
```
quadpy.quadrilateral.rectangle_points
```
is for anyone who really only wants to integrate over a cube with sides aligned to the axes. It lets you specify the "limits" and gives you the `(2, 2, whatever)` array.

This went undocumented as I didn't know anyone what actually using it.

**Comment by nschloe** [comment]
Alright, I coughed up a little more documentation for this:
https://github.com/nschloe/quadpy/tree/stroud-ball#quadrilateral

Will be part of the next release.

If you feel this isn't sufficient, feel free to reopen this issue.

**Comment by Dschoni** [comment]
Thank you for your work on this, on the package as a whole and your fast response! Indeed people are using your work.
