### ISSUE TITLE
Quadpy out of sync with orthopy since newest release

### ISSUE THREAD

**Issue by Pearlite** [nschloe/quadpy#125]
Since the most recent release of orthopy (0.2.0, two days ago), calls to orthopy.recurrence_coefficients.jacobi() no longer accept the 'mode' keyword argument (and potentially more has stopped working, but this is the first thing I ran into):

`File "/usr/local/lib/python2.7/dist-packages/quadpy/line_segment/gauss_kronrod.py", line 47, in __init__
    orthopy.recurrence_coefficients.jacobi(length, a, b, mode='numpy')
TypeError: jacobi() got an unexpected keyword argument 'mode'`

Suggested fix: specify orthopy 0.1.7 as requirement in setup.py for the time being, then update quadpy to work with the newest release of orthopy.

Thanks!

**Comment by nschloe** [comment]
Ah yes, that's right! Will fix this later this afternoon.

**Comment by nschloe** [comment]
Done.
