### ISSUE TITLE
[Feature] Use Knuth summation by default instead of Kahan

### ISSUE THREAD

**Issue by kostyfisik** [nschloe/quadpy#135]
Kahan provides less digits and needs more time. However, by default quadpy use Kahan only https://github.com/nschloe/quadpy/blob/6d49cc07e96d644bdcf039fd66a541208ce96794/quadpy/helpers/misc.py#L50 

Can probably be ported from C code below.

https://www.mathworks.com/matlabcentral/fileexchange/26800-xsum
- Kahan: The local error is subtracted from the next element. 1 to 3 more valid digits, 2 to 9 times slower. 
- Knuth: As if the sum is accumulated in a 128 bit float: about 15 more valid digits. 1.4 to 4 times slower. This is suitable for the most real world problems.

**Comment by nschloe** [comment]
Let me briefly acknowledge this excellent suggestion. Looking at the summation I quickly realized that it is much better implemented as a dot-product (https://github.com/nschloe/quadpy/pull/136/commits/c3cefbf265fdbf0154d71718fac784baf3784e45). Incidentally, the article referenced in xsum

Takeshi Ogita and Siegfried M. Rump and Shin'ichi Oishi,
Accurate Sum and Dot Product with Applications

also treats those. Stay tuned...

**Comment by nschloe** [comment]
Alright, I've now taken the time and created [accupy](https://github.com/nschloe/accupy) for exact sums and dot products. Dot products are still slow, but hopefully this will already help you.

**Comment by kostyfisik** [comment]
Great, thanks!
