### ISSUE TITLE
How to make an integration over a parametric line in 3D?

### ISSUE THREAD

**Issue by pedrohnv** [nschloe/quadpy#142]
Hello, I have a complex-valued function which argument is a 3D point. I want to do an integration of it over a line segment (parametrized in `t`). I get a `ValueError: operands could not be broadcast together with shapes (3,) (1,15) `. Here is the sample code:

```python
import numpy
from scipy import linalg
import quadpy

startPoint = numpy.array([0.5, 1.0, 1.2])
endPoint = numpy.array([-0.5, -1.0, 0.7])
length = linalg.norm(startPoint - endPoint)
gamma = 0.01 + 0.586j

def point(t):
    return startPoint + (endPoint - startPoint)*t

def integrand(t):
    pt = point(t)
    r1 = linalg.norm(pt - startPoint)
    r2 = linalg.norm(pt - endPoint)
    nf = (r1 + r2 + length)/(r1 + r2 - length)
    return numpy.log(nf)*numpy.exp(-gamma)

value, error_estimate = quadpy.line_segment.integrate_adaptive(integrand,[0,1],1e-10)
```

The error is raised because `t` is passed as an array. If I try to vectorize the `point` function using `numpy.vectorize`, then the error changes to `ValueError: setting an array element with a sequence.`. I can't think of a work around. Could you help me?

**Comment by nschloe** [comment]
First off, this
```python
nf = (r1 + r2 + length)/(r1 + r2 - length)
```
looks like a division by zero at _all_ points. You probably want to fix this first.

After that, you have multiple possibilities:

quadpy understands multidimensional integration limits, so something like
```python
quadpy.line_segment.integrate_adaptive(
    integrand,
    [numpy.array([0.5, 1.0, 1.2]), numpy.array([-0.5, -1.0, 0.7])],
    1e-10
    )
```
is legal. Also, if you're just messing around with the distances to the lengths, you probably don't need to convert to 3D-space at all. Isn't
```
r1 = length * t
r2 = length * (1-t)
```
after all?

**Comment by pedrohnv** [comment]
In my original code the start point and end point inside the function are of another line (`r` are the distances from the point in the line of integration to the tip points of another line). I messed that up when trying to isolate the error...

Doing as suggested, multidimensional limits, I've came up with a function that raises no error.
```
def integrand(t):
    point = t.T # had to transpose
    r1 = numpy.array( [linalg.norm(pt - p1) for pt in point] )
    r2 = numpy.array( [linalg.norm(pt - p2) for pt in point] )
    nf = (r1 + r2 + length)/(r1 + r2 - length)
    return numpy.log(nf)*numpy.exp(-gamma)

val, err = quadpy.line_segment.integrate_adaptive(
            integrand, [startPoint, endPoint], 1e-10)
```
Thank you for the help.
