### ISSUE TITLE
Cubature rules over the square.

### ISSUE THREAD

**Issue by alvisesommariva** [nschloe/quadpy#143]
Dear Nico,

first of all, many thanks for your job. Really impressive!

In case You may need it, at 

http://www.math.unipd.it/~alvise/sets.html

I have several sets, mostly for interpolation, on your regions. But also a file for cubature over the square that might be helpful for Your job:

http://www.math.unipd.it/~alvise/POINTSETS/set_amr_square.m

All the best,

Alvise Sommariva

**Comment by nschloe** [comment]
Hi Alvise,

I finally got around adding some of this! :)

On https://github.com/nschloe/quadpy/tree/master/quadpy/quadrilateral/sommariva you'll see that I've converted a bunch of schemes into JSON format to be consumed by quadpy. If you could convert the rest to rest to JSON, I'd be more than happy to add them to quadpy as well.

**Comment by alvisesommariva** [comment]
Dear Nico,

I think that I have done what was requested. I send You a zip file, as  
attached file.

Inside You will find:

1. My previous nodes in Matlab,
2. points_creator.m that is what I used to convert and save the sets  
(maybe it is useful for other translations into your format),
3. All the files, that look the same to yours.

All the best and thank You for Your work,

Alvise


Quoting Nico Schlömer <notifications@github.com>:

**Comment by nschloe** [comment]
Forgot the attachment?

**Comment by alvisesommariva** [comment]
Dear Nico,

I am pretty sure I attached the file. I hope it is not a problem with  
my mailer. I attach it again.

In case of problems see:

http://www.math.unipd.it/~alvise/NICO/NICO.zip

Have a good day,

Alvise


Quoting Nico Schlömer <notifications@github.com>:

**Comment by nschloe** [comment]
Alright, it's not included. Thanks!

**Comment by alvisesommariva** [comment]
Dear Nico,

I hope You were able to download the codes via web page.

Let me know if everything is fine.

Alvise

Quoting Nico Schlömer <notifications@github.com>:

**Comment by alvisesommariva** [comment]
Ad astra per aspera! :)
Alvise


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Nico Schlömer <notifications@github.com> Data: 26/11/18  20:27  (GMT+01:00) A: nschloe/quadpy <quadpy@noreply.github.com> Cc: alvisesommariva <alvise@math.unipd.it>, Author <author@noreply.github.com> Oggetto: Re: [nschloe/quadpy] Cubature rules over the square. (#143) 
All fine! :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nschloe/quadpy","title":"nschloe/quadpy","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/nschloe/quadpy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nschloe in #143: All fine! :)"}],"action":{"name":"View Issue","url":"https://github.com/nschloe/quadpy/issues/143#issuecomment-441765558"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nschloe/quadpy/issues/143#issuecomment-441765558",
"url": "https://github.com/nschloe/quadpy/issues/143#issuecomment-441765558",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [nschloe/quadpy] Cubature rules over the square. (#143)",
"sections": [
{
"text": "",
"activityTitle": "**Nico Schlömer**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@nschloe",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"nschloe/quadpy\",\n\"issueId\": 143,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/nschloe/quadpy/issues/143#issuecomment-441765558"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 298816582\n}"
}
],
"themeColor": "26292E"
}
]
