### ISSUE TITLE
Integration of function only accepting transposed points.

### ISSUE THREAD

**Issue by qTipTip** [nschloe/quadpy#145]
Hi!

Thanks for a great module - it's very impressive!

I have a question. Currently the integration relies on the integrand being defined as in your example:

```python
def f(x):
    return np.sin(x[0]) + np.cos(x[1])
```
where the numpy vectorisation takes care of input vectors of shape `x.shape = (2, N)`.
I am currently dealing with functions that assume the input is of shape `x.shape = (N, 2)`, as in the following example:

```python
def f(x):
    return np.sin(x[:, 0]) + np.cos(x[:, 1])
```
yielding errors like

```bash
    def integrate(f, simplex, scheme, dot=numpy.dot):
        flt = numpy.vectorize(float)
        x = transform(flt(scheme.points).T, simplex.T)
        vol = get_vol(simplex)
>       return vol * dot(f(x), flt(scheme.weights))
E       ValueError: shapes (2,) and (7,) not aligned: 2 (dim 0) != 7 (dim 0)
```

Would it be possible to support functions that accept ''transposed'' input?

**Comment by nschloe** [comment]
Why don't you simply transpose your function?

**Comment by nschloe** [comment]
Here's a little example that backs up my claim. Suppose you have three big arrays of the same shape that you want to multiply-and-add, `a*b + c`. Now, either the three arrays are `arr[0,...]`, `arr[1,...]`, `arr[2,...]` or `a[...,0]`, `a[...,1]`, `a[..., 2]`:
```
import numpy
import perfplot


perfplot.plot(
    setup=lambda n: (numpy.random.rand(3, n), numpy.random.rand(n, 3)),
    kernels=[
        lambda data: data[0][0]*data[0][1] + data[0][2],
        lambda data: data[1][:, 0]*data[1][:, 1] + data[1][:, 2],
       ],
    equality_check=False,
    labels=['a[0, :]', 'a[:, 0]'],
    n_range=[2**k for k in range(20)],
    logx=True,
    logy=True,
    )
```
Result:
![comp](https://user-images.githubusercontent.com/181628/36480258-efccdf48-170b-11e8-8f62-a1e82f2d9b3e.png)
`a[k]` is about twice as fast.

#### Message

In NumPy, better always use an ordering that makes sure your code puts the dots at the end (where you can omit them). Advantages:

  * Faster.
  * Clearer.
  * Works natively with quadpy. :smile:

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time!
