### ISSUE TITLE
Generating quadratures

### ISSUE THREAD

**Issue by zerothi** [nschloe/quadpy#151]
Thanks for this software!

I cannot create custom quadratures using the scheme proposed in the documentation.

See the section: **Generating your own Gauss quadrature in three simple steps**

I am using `quadpy` 0.11.4 and `orthopy` 0.5.3.

**Comment by nschloe** [comment]
I've updated to documentation now. (Earlier, I'd just moved over the code from orthopy without updating the documentation.)

**Comment by zerothi** [comment]
@nschloe thanks!
