### ISSUE TITLE
Missing Lebedev quadratures

### ISSUE THREAD

**Issue by sencer** [nschloe/quadpy#159]
Hi,

Although not quite my expertise area, I think the code cannot generate some basic Lebedev quadratures.

Most simple of these being, just a single node at the origin.

Also:

    {
      "a3": [
        [5.7735026918962575e-01]
      ],
      "degree": 2
    }

and:

    {
      "a2": [
        [7.07106781186547524e-01]
      ],
      "degree": 4
    }

In both cases degree is just an arbitrary number that I have written in order to make it work with your code.

I came across this issue when I was trying to implement the algorithm described in https://aip.scitation.org/doi/full/10.1063/1.5008630.

**Comment by nschloe** [comment]
> Most simple of these being, just a single node at the origin.

Lebedev quadratures are quadratures for the _sphere_, i.e., the surface of a ball. The origin is not part of it.

> In both cases degree is just an arbitrary number that I have written in order to make it work with your code.

Could you reformulate this? I can't quite catch what you're trying to say.

**Comment by sencer** [comment]
OK, let me try: I don't know what the "degree" should be for these two cases, so I just threw an arbitary number; but shouldn't the edges and the faces of the octahedron be included as separate cases, as well? I might very well be wrong though.

**Comment by nschloe** [comment]
Ah, I see now: You're suggesting two more quadratures, but don't know exactly of what degree they are. Alright.

Can you give me a reference for those? Or do they come from the article you mentioned?

**Comment by sencer** [comment]
Yes, it is from the article I mentioned earlier. They have a reference implementation at  10.5281/ZENODO.1054550; which is incomplete and not working. Yet it still provides a `Lebedev` class.

You can check it four yourself, but: the class is initiated as `Lebedev(n)` with n being the number of points in the desired quadrature. It can be one of [1, 6, 8, 12, 14, 26, 38, 50, 74...]. I can recreate the same quadrature with code for each of these numbers, except for 1, 8 and 12. So I thought, initially, that you somehow skipped those. Now I am not quite sure.

**Comment by nschloe** [comment]
Alright. The two schemes that were missing from quadpy were `leb8` and `leb12`. I've included them now as `Lebedev("3b")` and `Lebedev("3c")`. The reason why there weren't there before is that that both only have degree 3, just like `Lebedev("3a")`, and both have more points than ``Lebedev("3a")`. I don't see a reason to use them, but maybe someone else does.

Let me know if you have any more problems.

**Comment by sencer** [comment]
Great thanks!
