### ISSUE TITLE
Usage question 

### ISSUE THREAD

**Issue by GProtoZeroW** [nschloe/quadpy#163]
I would like to use this library to find a sudo numerical Laplace transform of some discrete data. So I know that I would need a weight function of 
```
Whight=lambda sigma, omega: scipy.exp(sigma+1j*omega)
``` 
but how would I construct the kernel around `f` which is my input data 1D vector but besides that I have no idea on how to set this up with quadpy using the Quadrilateral or the RabinowitzRichter integration scheme or if its even doable 

so for exsample by `f` data may be given by 
```
f=np.linspace(0,5,150)
```
as a basic exsample

**Comment by nschloe** [comment]
I can't really follow here. What's the integral that you would like to compute?

**Comment by nschloe** [comment]
But `f` is a function in the Laplace transform, not a vector.

**Comment by GProtoZeroW** [comment]
I am saying `f` is a 1D vector in the in terms of numpy terminology. For the example, it would be the numerical values of $f=ax+b$  but it could be the discrete values of any one-dimensional function that is needing to be transformed.  The reason I need Laplace is that the Fourier transform only shows the harmonics that make up the function, not any exponential growth or damping that occurs in most systems

**Comment by nschloe** [comment]
Alright, so you have a one dimensional function `f` that you can evaluate everywhere on `(0, infty)` and you'd like to compute the integral
```
I(s) = int_0^infty exp(-s*t) f(t) dt
```
Correct?

In this case, you'll need [Gauss-Laguerre](https://github.com/nschloe/quadpy#1d-half-space-with-weight-function-exp-r). First transform your integral into the form
```
I(s) = int_0^infty exp(-x) s f(x/s) dx
```
so you'll need to plug `lambda x: s * f(x/s)` into Gauss-Laguerre.

**Comment by GProtoZeroW** [comment]
Correct and where 90% there. But I want to avoid using a fitting, spline or otherwise, of f from the data because it still has noise in it and I want to try to use the moment generating property of the Laplace transform to find the mean in the noise. So let's do for example

```
import numpy as np
f=np.linspace(0,5,150)
f=np.exp(.001*np.arange(len(f)))
f=f+np.random.normal(-0.001, .01, len(f))
```

**Comment by nschloe** [comment]
I would think quadpy is the wrong tool for the task then. quadpy only does one thing: It computes numerical approximations of integrals of given functions. If you cannot evaluate your function everywhere, you'll need to use your own approach.

**Comment by GProtoZeroW** [comment]
So what you're saying is that I would have to use a high fitting spline or otherwise on the data to then feed into quadpy, but again what is `s`.

**Comment by nschloe** [comment]
> I would have to use a high fitting spline

Spline or something else, quadpy needs a function that can be evaluated everywhere in the domain.

> but again what is s.

https://en.wikipedia.org/wiki/Laplace_transform#Bilateral_Laplace_transform

**Comment by GProtoZeroW** [comment]
I know what $s$ is in many a mathematical and physical context see for ex [Laplace Transform Explained and Visualized Intuitively
](https://www.youtube.com/watch?v=6MXMDrs6ZmA) by Physics Videos by Eugene Khutoryansky.
But in the code to use  GaussLaguerre what would it be. 

Seriously let's get this working because there is not a good numerical Laplace transform but for Signals and Systems, its used all the time analytically. So I still think quadpy can do this and doing this would be a major power boost to python over matlab.

**Comment by GProtoZeroW** [comment]
yes and I would then sup in `s=sigma+1j*omega` where I then would insert values for `sigma` and `omega` from numpys meshgrid to then get a nice plot of how the system from the data would then respond to an input in each quadrant and near poles and zeros, ect ect. but give me a concrete example code because im an idiot, for example, do I use 
``` 
from sympy import *
s=symbols('s')
```
for `s` in the code
```
import numpy 
import quadpy

def f(x):
    return numpy.sin(x[0])

#what is `s` here

val = quadpy.e1r.integrate(
    lambda x: s*f(x/s),
    quadpy.e1r.GaussLaguerre(5, alpha=0)
    )
val
```
besoue if i try running this without defining what `s`is i get 
```
NameError: name 's' is not defined
```

**Comment by nschloe** [comment]
> but give me a concrete example code

Simply check out the main readme:
https://github.com/nschloe/quadpy#1d-half-space-with-weight-function-exp-r. It doesn't get more concrete than that.

> #what is `s` here

I'd start with any value that you're interested in. If that works for you, you can either loop over all `s` that you want, or put in a vector of those to integrate them all at once.
