### ISSUE TITLE
Too many subscripts for einstein sum

### ISSUE THREAD

**Issue by e-eight** [nschloe/quadpy#164]
Hi Nico,

I wanted to use quadpy for my integrations. I tried the line_integral example given in the readme. It gives me a `ValueError: einstein sum subscripts string contains too many subscripts for operand 0`. 
I am not sure what is going wrong. Any ideas?

Thanks.

**Comment by nschloe** [comment]
I'm guessing your function spits out the wrong data shape. Can you provide a minimal example?

**Comment by e-eight** [comment]
It is literally the line_segment example in the readme file.
`val = qp.line_segment.integrate(lambda x: np.exp(x), [0.0, 1.0], qp.line_segment.GaussPatterson(5))`

**Comment by nschloe** [comment]
Cannot reproduce. This
```python
import quadpy as qp
import numpy as np

val = qp.line_segment.integrate(
    lambda x: np.exp(x),
    [0.0, 1.0],
    qp.line_segment.GaussPatterson(5)
    )

print(val)
```
gives
```
1.7182818284588917
```
on my machine. (The exact value is `exp(1) - exp(0)` which is approximately `1.718281828459045`, so this is correct.)

**Comment by e-eight** [comment]
I see. This is the error that I am getting.
![1533740552](https://user-images.githubusercontent.com/3883241/43845796-69932fc0-9af2-11e8-9a65-157bc18250f6.png)

**Comment by nschloe** [comment]
Looks very much like an error in your numpy installation.

**Comment by e-eight** [comment]
Edit: Tried it again after restarting ipython. And it worked this time. Got the same answer as you. Possibly some numpy issue. Thanks for looking in to it.
