### ISSUE TITLE
Error in Gauss-Hermite formula?

### ISSUE THREAD

**Issue by cdagnino** [nschloe/quadpy#169]
Hi,

I'm using quadpy 0.12.5
Maybe I'm missing something, but I think there's an issue with the way the Gauss-Hermite integration is coded.

When looking at the [wikipedia page](https://en.wikipedia.org/wiki/Gauss%E2%80%93Hermite_quadrature), I see there should be a Pi^(-0.5) term added and a rescaling of the gauss-hermit points.

```
import quadpy
import numpy as np
from scipy import stats
from scipy import integrate

def f(x):
    return x**2

#Manual Gauss-Hermite
points, weights = np.polynomial.hermite.hermgauss(5)
mu, sigma = 0, 1
rescaled_points = np.sqrt(2)*sigma*points + mu

manual_gauss_hermite = np.pi**(-0.5)*np.dot(f(rescaled_points), weights)

#Manual trapezoid
xvals = np.linspace(-10, 10, num=100)
yvals = f(xvals) * stats.norm.pdf(xvals)
trapezoid_int = integrate.trapz(yvals, xvals)


#Gauss-Hermite integration
quadpy_integration = quadpy.e1r2.integrate(f, quadpy.e1r2.GaussHermite(5))


print("Manual Gauss-Hermite: ", manual_gauss_hermite)
print("Trapezoid: ", trapezoid_int)
print("Quadpy Integration: ", quadpy_integration)
```

gives

```
Manual Gauss-Hermite:  0.9999999999999999
Trapezoid:  1.0
Quadpy Integration:  0.8862269254527577
```

So the trapezoid rule agrees with the rewrite of gauss-hermite, but not with the gauss-hermite procedure contained in `quadpy`.

**Comment by nschloe** [comment]
When applying Hermite quadrature, note that, given `f`, it approximates the integral
```
int_{-infty}^{+infty} f(x) exp(-x^2)
```
The true result of `int_{-infty}^{+infty} x^2 exp(-x^2)` is `sqrt(pi)/2`, so quadpy is right.

**Comment by cdagnino** [comment]
My bad! I've seen so much Gauss-Hermite used to approximate f(y) where y is a normally distributed variable that I thought that was the canonical representation of Gauss-Hermite.

Would you be interested in a pull request for  the rescaling for the normally distributed case? I guess it's better to write a new function in that case

**Comment by nschloe** [comment]
You mean a function that already incorporates the term `exp(-x ** 2)`?

**Comment by cdagnino** [comment]
I mean a function that uses Gauss-Hermite polynomials to integrate a function `f(y)` where `y ~ N(mu, sigma)`. The integral would look this way:

`\int f(y) stats.norm.pdf(y, mu, sigma) dy = \int_{-\infty}^{+\infty} \frac{1}{\sigma \sqrt{2\pi}} f(y) \exp \left( -\frac{(y-\mu)^2}{2\sigma^2} \right)  dy`

The integration procedure could be called this way (not sure about the name of course!)

`quadpy.function_of_a_normal.integrate(f, quadpy.e1r2.GaussHermite(5))`

**Comment by nschloe** [comment]
Not a big fan of this. One can easily transform the integral into one of the form
```
int_{-infty}^{+infty} f(x) exp(-x^2)
```
and is should be the responsibility of the user to do so.

**Comment by cdagnino** [comment]
Ok! But, just in case, I don't think you can transform the integral into that form without rescaling the nodes.

**Comment by nschloe** [comment]
```
\int_{-\infty}^{+\infty} \frac{1}{\sigma \sqrt{2\pi}} f(y) \exp \left( -\frac{(y-\mu)^2}{2\sigma^2} \right) dy
= [x = (y - mu) / sqrt(2) / sigma]
\int_{-\infty}^{+\infty} \frac{1}{\sqrt{\pi}} f(x) \exp(-x^2) dx
```
