### ISSUE TITLE
Inability to reach desired precision causes crashes

### ISSUE THREAD

**Issue by CalebBell** [nschloe/quadpy#174]
Hi Nico,
I've been looking at quadpy's implementation of integrate_adaptive for line segments to better understand the technique. I find your code very easy to follow and understand; thank you very much. The project is also, for sure, unparalleled in its coverage! Your project is a fantastic resource.

I noticed that if quadpy cannot obtain the requested precision, it does not fail gracefully. It simply keeps trying in the loop integrate_adaptive, I believe increasing the number of intervals. For me, this leads to crashes of Python, due to running of of memory. I was wondering if this was by design? Or if there was any sort of logic that would be appropriate to add along the lines of "giving up"? The example I ran into is as follows.

```
from quadpy.line_segment import integrate_adaptive
def f(x):
	return 1.2*x*x*x - 1.2*x*x + 14*x + 1.23
val, error_estimate = integrate_adaptive(f, [0.0, 10000], 1e-5, kronrod_degree=7)

```
This integral isn't important to me; just me trying to learn and explore different scenarios. I'm not sure what scipy's quad is doing, but it simply ignores the requested precision on the same problem and returns with a much large error than requested.

Sincerely,
Caleb

**Comment by nschloe** [comment]
This is quite a legitimate concern; I think it even came up before. I should probably add some sort of `min_interval_length` parameter.

**Comment by nschloe** [comment]
Ah wait, I already did that. :) `minimum_interval_length=0.0` is the default; set it to something greater than 0 to avoid the crash.
