### ISSUE TITLE
Quadpy for triangles - non regular fonction, does it works?

### ISSUE THREAD

**Issue by juliensammut** [nschloe/quadpy#184]
Hello,
sorry for my English (i'm french).
I try tu use quadpy.triangle.integrate with a function (material comportment) non "regular" (0 if < 0 else value).
I guess this function couldn't be integrate (pb of derivate?) on a triangle, it looks like the function is choose with the condition find on the 3 points of the triangle (function all()). is it True or is it the way it is defined ??
Thanks for your help

this is the programm

```python
def NM0xM0y_c_ELS(points_cont_xy, n, eps0, alpha, beta):
	
	pts=np.array(points_cont_xy)
	nb=pts.shape[0]	
	
	N=0.
	M0x=0.
	M0y=0.
	Scomp=0.
	
	for i in range(nb-1):
		triangleOAB = np.array([[0,0],pts[i],pts[i+1]])
		signe = np.sign(pts[i,0]*pts[i+1,1]-pts[i,1]*pts[i+1,0])

		epsilon = lambda pt : eps0+alpha*pt[0]+beta*pt[1]
		sigma = lambda pt : ((200000/n*epsilon(pt)/1000) if all(epsilon(pt)>=0) else pt[0]*0)
	
		sigma_y = lambda pt : pt[1]*sigma(pt)
		sigma_x = lambda pt : pt[0]*sigma(pt)
		
		N += signe*quadpy.triangle.integrate(sigma,triangleOAB, quadpy.triangle.Strang(10))
		M0x += signe*quadpy.triangle.integrate(sigma_y,triangleOAB, quadpy.triangle.Strang(10))
		M0y += signe*quadpy.triangle.integrate(sigma_x,triangleOAB, quadpy.triangle.Strang(10))

	res = np.array([N,M0x,M0y,Scomp])
	return res
```

**Comment by juliensammut** [comment]
Hi again,
Let me try to rephrase:
I am trying to integrate a function defined by parts over a triangle.
To achieve that, I defined my function with some conditions. The integration doesn’t seem to work when the integrated function is defined with the conditions. 
Also, it seems to me that these conditions are applied only on the three points defining the triangle. What happens with the rest of the domain? 
Thanks

To illustrate the problem, here’s my code for the integration of a sign function (-1 or 1)

def issue_simple_exemple():
	triang = np.array([[0,0],[-1,1],[2,1]])
	funct = lambda pointxy : np.sign(pointxy[0]) #-1 for x<0, 1 for x>0
	result = quadpy.triangle.integrate(funct,triang, quadpy.triangle.Strang(10))

	return result

**Comment by nschloe** [comment]
Alright, I get it now. You're expecting the result to be close to the true result 0.0, but it won't come out this way.

The reason for this is the fact that all quadrature methods in quadpy (and most in literature) are designed to integrate _polynomials_ of a certain degree exactly. If you don't have a polynomial, but a smooth function (which can be approximated well by polynomials), you can expect good approximation. You, on the other hand, try to integrate a function that is very unsmooth -- in fact, it's not even continuous! You cannot expect anything here. Simply put, numerical quadrature is the wrong tool for the task.

**Comment by juliensammut** [comment]
thanks for your answer !
