### ISSUE TITLE
Wedge schemes

### ISSUE THREAD

**Issue by dbeurle** [nschloe/quadpy#185]
Would it be possible to get some additional wedge (or triangular prism) schemes?  One that comes to mind is "New computationally efficient quadrature formulas for triangular prism elements" by Kubatko and friends.

Related #117.

**Comment by nschloe** [comment]
quadpy is a bit sort on prism and wedge schemes, so yeah, sure it would be possible.

**Comment by dbeurle** [comment]
Thank you very much!
