### ISSUE TITLE
integration over multiple intervals

### ISSUE THREAD

**Issue by rroohhh** [nschloe/quadpy#187]
I am not sure, if I missed something or this is just not possible, but is there a way to use adaptive integration over multiple intervals at once and get the value for each of the intervals (instead of the total)?

Something like this:
```python
intervals = [[1.0, 2.0], [1.0, 3.0]]
[quadpy.line_segment.integrate_adaptive(lambda x: np.ones_like(x), interval, 1e-8) for interval in intervals]
```
but using numpy vectorization.

Related to that: is there a integration scheme, that is optimized for multiple, overlapping intervals?

**Comment by rroohhh** [comment]
@nschloe ping

**Comment by nschloe** [comment]
Hi Robin, you're right, it should actually return the results on the individual intervals, not the sum. Looking at this right now.
