### ISSUE TITLE
Unclear documentation of vectorised integration

### ISSUE THREAD

**Issue by burnpanck** [nschloe/quadpy#188]
First of all thanks for making this library public!
Similar to #167, I'm trying to integrate a function over a line-segment for a set of independent (non-integration) parameters. I was hoping to vectorise this by simply returning the function evaluated for all parameters simultaneously as an array. However, I got bitten by the dimension mismatch too. Furthermore, it is not totally clear how the dimensionality should be in the first place. An example without explanation, such as
```
def f(x):
    return numpy.array([numpy.exp(x), numpy.sin(x)])
```
doesn't help much, because I still don't know the dimensionality of the input `x`, or how it matches to the output and the vectorised domains.

It would be helpful, if the README would call out the API for vectorisation in a bit more detail, exactly where the vectorisation features are advertised. For example, the following would be the documentation of the vectorisation how I could imagine implementing such an API:

> The domain is specified using `k` coordinates in `d` dimensions.
> A domain specification given as array with shape `(k,u,v,d)` performs
> vectorised integrals over `u*v` domains.
> Generally, for vectorised domains with shape `domain_shape`,
> the domain specification is given as an array of shape `(k,)+domain_shape+(d,)`.
> In the special case of line-integrals, the dimension index is dropped,
> and the domain specification is given as array of shape `(2,)+domain_shape`.
>
> The integration scheme will evaluate the integrand on `n` points (related to the order) simultaneously,
> therefore, the input to the integrand callback will be an array of shape `domain_shape+(d,n)`, or for line integrals, `domain_shape+(n,)`.
> If the integral shall further be computed for `i*j` integrands simultaneously
> on the same domain(s),
> with the integrands conceptually arranged in a shape of `integrand_shape` (e.g. `(i,j)`),
> the integrand callback may return an array of dimension `integrand_shape+domain_shape+(d,n)`.
> The result integral is then returned as an array of shape `integrand_shape+domain_shape`.

However, that does not seem to be the API quadpy is currently offering. It would be helpful if the API could be described somewhere in a similar way.

**Comment by nschloe** [comment]
>  because I still don't know the dimensionality of the input x, or how it matches to the output and the vectorised domains.

When returning an array of the wrong dimensionality, one gets something like
```
AssertionError: Illegal shape of f(x) (expected (..., 5, 12), got (12,))
```
Isn't that clear enough? I've added a text to the wiki https://github.com/nschloe/quadpy/wiki#dimensionality-of-input-and-output-coordinates, what do you think?

**Comment by burnpanck** [comment]
> Isn't that clear enough?
For me, it wasn't enough for immediate understanding. I would have preferred variable names over simple numbers: While I can easily create an `f(x)` that outputs an array by shape `(..., 5, 12)`, integration only works as expected if each array element contains the correct value. For that, I need to know what the array index stands for.
The wiki-text on the other hand is very helpful. It might make sense to link to it from the README. There are two smaller details still missing though; the text does not seem to be exactly correct for adaptive line-integrals (maybe point out that `n` is variable in adaptive integration and `d` is dropped in line-integrals), and it seems "parallel" integration (i.e. multiple integrands) is indeed possible by returning the output as `(...,n,p)`, with the leading dimensions corresponding to multiple integrands. Is that even correct? The resulting integrals seemed reasonable to me.

**Comment by nschloe** [comment]
> Is that even correct? 

It is.

**Comment by nschloe** [comment]
> It might make sense to link to it from the README.

Indeed. I've changed it locally and will push it sometime soon.

> and it seems "parallel" integration (i.e. multiple integrands) is indeed possible by returning the output as (...,n,p)

Added this to the wiki.
