### ISSUE TITLE
Missing assignment to max_steps in _solve_expx_x_logx

### ISSUE THREAD

**Issue by oliversheridanmethven** [nschloe/quadpy#189]
In the call to `_solve_expx_x_logx` from `tanh_sinh_lr` the `max_steps`  value is not assigned in the function call. Also there is no way to vary the tolerance in the call from the external function.

**Comment by nschloe** [comment]
Indeed, `max_steps` is meant for the actual tanh-sinh steps, not the initial approximation of the step size `h`. Has the lack of control been a problem for you here? What's your `eps`?

**Comment by oliversheridanmethven** [comment]
It was proving problematic. I had been trying to evaluate an approximation to the `scipy.norm.ppf` and compute the MSE using `quadpy`, and found that the `_solve_expx_x_logx` function kept throwing an assertion error. It was struggling to find a solution by the Newton scheme. This was for `eps` as small as 0.01 and me increasing `max_steps` to 10000+. Ultimately I gave up trying to use the suite and couldn't find the energy to produce a MWE to replicate the issue.

**Comment by nschloe** [comment]
I got it reproduced with
```
import numpy
import quadpy

quadpy.line_segment.tanh_sinh(numpy.sin, 0.0, 2.0, 1.0e-2)
```
Looking into it. For now, simply decrease eps to 1.0e-6 or lower, that should work.

**Comment by nschloe** [comment]
I just fixed this; check out the section in the README. https://github.com/nschloe/quadpy#tanh-sinh-quadrature
