### ISSUE TITLE
Usage of np.array instead of np.asarray in ball/tools.py integrate function

### ISSUE THREAD

**Issue by dariusarnold** [nschloe/quadpy#200]
When reading the code for the integration function for a ball, I was wondering why `np.array` was used instead of `np.asarray`. The former always copies the argument, while the latter doesn't do so if the input is already an array. The copy has a cost associated with it. I just quickly tested it in IPython:
```python
a = np.random.rand(3, 2, 21206, 6)                                                         
%timeit np.asarray(a)                                                                      
>>> 261 ns ± 2.16 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
%timeit np.array(a)                                                                        
>>> 323 µs ± 17.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
So, roughly thousand times slower. Of course, because of vectorization integrate doesn't have to be called often, so the impact is low. I was just trying to figure out if a copy is actually needed.

**Comment by nschloe** [comment]
Thanks, I've fixed this now.
