### ISSUE TITLE
The sphere example from README.md is not working 

### ISSUE THREAD

**Issue by mretegan** [nschloe/quadpy#202]
I was a bit surprised by this and I assume I'm doing something wrong because I did not see this reported previously. I've tried a few recent versions including the current master branch. I get this traceback:

```python
Traceback (most recent call last):
  File "quadpy_sphere.py", line 4, in <module>
    scheme = quadpy.sphere.lebedev_019()
AttributeError: module 'quadpy.sphere' has no attribute 'lebedev_019'
```

**Comment by nschloe** [comment]
I merged a big PR yesterday with those changes, but haven't released them to PyPi yet. If you installed quadpy via `pip`, stick to the documentation on https://pypi.org/project/quadpy/. I'll make a release in the coming days.

**Comment by nschloe** [comment]
Alright, 0.13.0 is out.
