### ISSUE TITLE
Attributes missing?

### ISSUE THREAD

**Issue by clionFHR** [nschloe/quadpy#204]
Hello,

I have tried to execute the documentation example for triangle integration 

`scheme = quadpy.triangle.xiao_gimbutas_05()`
`scheme.show()`
`val = scheme.integrate(lambda x: numpy.exp(x[0]), [[0.0, 0.0], [1.0, 0.0], [0.5, 0.7]])`

but I get the following error:

`AttributeError: module 'quadpy.triangle' has no attribute 'xiao_gimbutas_05'`

Has something been recently changed in quadpy? I have tried uninstalling and re-installing the module, but to no avail... (I am using Python 3.7.1)

Thank you!

**Comment by nschloe** [comment]
It's not released yet. Will do so in the coming days.

**Comment by clionFHR** [comment]
Thanks for the reply!
Will the old syntax still be valid, or do I have to adjust my code?

**Comment by nschloe** [comment]
I've had to make a bunch of backwards-incompatible changes so you'll have to adjust you're code. I'll bump  the version to 0.13.0 though, so if you want to do it it now you can always depend on `quapdy < 0.13.0`.

**Comment by nschloe** [comment]
Alright, 0.13.0 is out.
