### ISSUE TITLE
extra arguments in integration

### ISSUE THREAD

**Issue by paddyroddy** [nschloe/quadpy#208]
Say I have a function
```
def f(x, a):
    return x + a
```
in scipy I could integrate this using `scipy.integrate.quad(f, 0, 1, args=(a))`. Is there a way to use extra arguments with quadpy?

**Comment by nschloe** [comment]
Never thought about it. Can't you just define `a` outside of `f`?

**Comment by paddyroddy** [comment]
In my own example not easily but I guess I could do a workaround for it, thanks

**Comment by nschloe** [comment]
> In my own example not easily

If you have a function `f(x, a)` like
```python
def f(x, a):
   return x + a      

scipy.integrate.quad(f, 0, 1, args=(42.1415))
```
you can always wrap it like
```python
def f(x, a):
   return x + a

scheme = quadpy.line_segment.legendre(5)
scheme.integrate(lambda x: f(x, 42.1415), [0.0, 1.0])
```
