### ISSUE TITLE
Add : passing arguments for parametric integrals

### ISSUE THREAD

**Issue by simbilod** [nschloe/quadpy#216]
Are there any plans to allow scheme.integrate() to take parametric arguments the way scipy.integrate.quad() does?

E.g. I am trying to do something like [this](https://stackoverflow.com/questions/51173981/lambdify-a-parametric-integral) with complex vector functions. The relevant part is here : 
```python
def integral_as_quad(function, limits):
    x, a, b = limits
    param = tuple(function.free_symbols - {x})
    f = sp.lambdify((x, *param), function, modules=['numpy'])
    return quad(f, a, b, args=param)[0]
```
and currently scheme.integrate() does not take a args=param equivalent argument.

Great work and thanks!

**Comment by nschloe** [comment]
I've never seen much use for `args`. Can't you simply wrap your function `f` like
```python
def f(x, param):
    return something

def g(x):
    param = something_else
    return f(x, param)
```
?

**Comment by simbilod** [comment]
Good idea, not sure why they didn't go with that in the example I posted since the recursive lambdification seems to give the integral a fully numeric expression with only the integration symbol. Thanks!
