### ISSUE TITLE
Getting theta and phi angles for Lebedev quadrature

### ISSUE THREAD

**Issue by Andersmb** [nschloe/quadpy#224]
I wanted to obtain the theta and phi angles for the lebedev quadrature, but I am not sure how to do this. I can't find the documentation for the sphere module. I thought perhaps the `quadpy.sphere.lebedev_035().points` would return the angles, but I don't recognize the numbers.

**Comment by nschloe** [comment]
You're probably looking for
```
import quadpy

scheme = quadpy.sphere.lebedev_035()
scheme.azimuthal_polar
```
If you use IPython, you can create the scheme object and then <TAB> your way around it, e.g.,
```
import quadpy
scheme = quadpy.sphere.lebedev_035()
scheme.<TAB>
```
will show you
```
azimuthal_polar       integrate_spherical() show()
citation              name                  weights
degree                plot()
integrate()           points
```
