### ISSUE TITLE
Assignment of integration domains with functions

### ISSUE THREAD

**Issue by mrenFHR** [nschloe/quadpy#226]
Hi,
thanks at first for all your effort writing this library!
My problem is about integrating a set of functions over different domains (in my case the different cells of a tetrahedron mesh). The used functions are only defined on parts of the domain, so it does not make sense to integrate them over the whole domain.
Giving quadpy the set of functions and the set of domains as input, it will now compute the integrals of _all_ functions over _all_ domains, which seems a bit wasteful in terms of performance (the result is 0 mostly). Is there a possibility to assign the subdomains with their functions so the additional integrals are not computed any more?
I could of course use a for loop over all subdomains, but this seems a bit adverse for the performance because it is not vectorized.
Thanks!

**Comment by nschloe** [comment]
I understand the problem. I can't think of a better way than looping right now, tbh. The thing is that you have different domains _and_ different functions, so the integrals have nothing to do with each other, except perhaps that you want to use the same scheme for every integration. Hm.

**Comment by mrenFHR** [comment]
Hm okay, I see. Then I will stick to the for loop for now. Thanks nevertheless for the quick answer!

**Comment by nschloe** [comment]
> The used functions are only defined on parts of the domain, so it does not make sense to integrate them over the whole domain.

Are you talking about FEM trial/test functions here actually?

**Comment by mrenFHR** [comment]
Almost, in this case its (SWG) basis functions for Method of Moments.

**Comment by nschloe** [comment]
Ah okay. I'm not familiar with that.
