### ISSUE TITLE
Inconsistent ndims of Gauss-Patterson weights

### ISSUE THREAD

**Issue by TheBB** [nschloe/quadpy#227]
quadpy.line_segment.gauss_patterson(0).weights.shape  # => (1,1)
    quadpy.line_segment.gauss_patterson(1).weights.shape  # => (3,)

The point arrays seem to be consistently one-dimensional.

**Comment by nschloe** [comment]
Well spotted! I'm looking at it right now.

**Comment by nschloe** [comment]
Fixed now.
