### ISSUE TITLE
vs. MATLAB's Gauss-Kronrod

### ISSUE THREAD

**Issue by OverLordGoldDragon** [nschloe/quadpy#232]
Thanks for your implementation. 

Any differences worth noting in [quad](https://github.com/nschloe/quadpy/blob/master/quadpy/line_segment/_tools.py#L16)'s implementation vs. [MATLAB](https://www.mathworks.com/help/matlab/ref/quadgk.html)'s?

**Comment by nschloe** [comment]
I don't know MATLAB's implementation.
