### ISSUE TITLE
Infinite interval for Gauss-Kronod

### ISSUE THREAD

**Issue by OverLordGoldDragon** [nschloe/quadpy#235]
I doubt [`quad`](https://github.com/nschloe/quadpy/blob/master/quadpy/line_segment/_tools.py#L16) can handle `intervals=(-np.inf, np.inf)` - this said, is specifying a sufficiently large interval for a given function a viable alternative? Any stability / imprecision caveats? Thanks

**Comment by nschloe** [comment]
Gauss-Kronrod, like many other integration methods, handles _polynomial_ integration exactly, and by extension, all _smooth_ functions. The integral of polynomials on (-inf, inf) however is undefined, so it wouldn't make much sense to use it here.

First find out if your integrand is of a particular type. Does it feature exp(-x^2). Gauss-Hermite. exp(-x) Gauss-Laguerre.

Another option: Do a variable replacement to a finite domain via arctan or x/(x+1), and use Gauss-Kronrod on that.

**Comment by OverLordGoldDragon** [comment]
@nschloe The integrand does feature `exp(-x**2)`, and is convergent; the context is wavelet filtering, and I'm porting a MATLAB Toolbox which uses Gauss-Kronod on [this line](https://github.com/ebrevdo/synchrosqueezing/blob/master/synchrosqueezing/stft_iw.m#L75); wtilftn has an exp defined [here](https://github.com/ebrevdo/synchrosqueezing/blob/master/synchrosqueezing/wfiltfn.m#L59).

I'm unfamiliar with the complete integrand in question, however, or what limits would sufficiently approximate it - but I can try increasing them until convergence is apparent. The question then is, is there anything worth noting in quad's implementation for large limits?

**Comment by nschloe** [comment]
>  The question then is, is there anything worth noting in quad's implementation for large limits?

There's nothing special about large limits.

I'd try variable transformation first though, you don't have to think about when to cut off then.

**Comment by nschloe** [comment]
I might add a function that allows automatic variable transformation in the future. Let's reopen to keep track.

**Comment by nschloe** [comment]
Alright, fixed now in `quadpy.quad`.
