### ISSUE TITLE
Divide by zero in quadpy.quad on vector-valued function

### ISSUE THREAD

**Issue by alienbrett** [nschloe/quadpy#249]
When using quadpy.quad, script returns divide by zero warning, before some strange behavior:

/quadpy/line_segment/_gauss_kronrod.py:167: RuntimeWarning: invalid value encountered in true_divide
/quadpy/line_segment/_tools.py:61: RuntimeWarning: invalid value encountered in less
  is_good, _numpy_all_except_last(error_estimate < eps_abs)
/quadpy/line_segment/_tools.py:65: RuntimeWarning: invalid value encountered in less
  is_good, _numpy_all_except_last(error_estimate < eps_rel * numpy.abs(val)),

After each iteration of my intergrand function, the input vector length doubles:

```python3
def integrand(exp_price):
        print( 'exp_price shape:',exp_price.shape)
        fax     = np.vectorize( lambda exp_price: pnl_obj.weighted_pnl  ( weights, exp_price )) (exp_price)
        # fax shape: (15,)
        dfdx    = np.array ( [dpnl_obj.weighted_pnl ( weights, x ) for x in exp_price] )
        # pa shape: (15, 266)
        pa      = np.vectorize( desired_obj.eval) (exp_price)
        # pa shape: (15,)
        z = np.multiply(
            ((pa-fax)*2).reshape(-1,1),
            dfdx
        ).T
        # z shape now: (266, 15)
        print('z shape: ', z.shape)
        return z

# Perform vector integration over interval
# val, err = quadpy.line_segment.integrate_adaptive( integrand, bounds)
val, err = quadpy.quad( integrand, (100,200)
```

Runs output with input exp_price shape
(15,)
(30,)
(60,)
... Until it slows to a crawl. Clearly this isn't correct behavior, the function isn't even preserving dimension across calls.
It looks like each call appends form of the integrand function output into the next input,

Please let me know what you manage to find, and if there's anything I can do to alleviate this

**Comment by nschloe** [comment]
Your MWE has syntax errors. Please correct them so I can copy and paste the code and reproduce the error.

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen with a working MWE at any time.
