### ISSUE TITLE
Quadpy has really high error / Integration error Tolerances (abs: 1.49e-08, rel: 1.49e-08) could not be reached with the given max_num_subintervals (= 50) while scipy works fine.

### ISSUE THREAD

**Issue by charelF** [nschloe/quadpy#255]
Original question: https://stackoverflow.com/questions/61202987/quadpy-integrationerror-tolerances-abs-1-49e-08-rel-1-49e-08-could-not-be?noredirect=1#comment108272913_61202987

---

I am using quadpy to integrate a function in python.

## Function

    import numpy as np
    T = 2*np.pi 

    def ex1(t):
        return np.where(np.logical_and((t%T>=0), (t%T<np.pi)), t%T, np.pi)

The function is periodic, this is its plot:

    x = np.linspace(0, 6*T, 1000)
    plt.plot(x, ex1(x))
    plt.grid(True)
    plt.show()

[![enter image description here][1]][1]

## Problem

I am trying to integrate this function:

    from scipy.integrate import quad
    import quadpy

    print(quadpy.quad(ex1, 0, 3))
    print(quad(ex1, 0, 3))

produces

    (array(4.5), array(1.41692995e-19))
    (4.5, 4.9960036108132044e-14)

On an interval from 0 to 3, everything works fine.
However If I increae the interval to e.g. 4, scipy still works.

    print(quad(ex1, 0, 4))

produces

    (7.631568411183528, 1.0717732083155035e-08)

but

    print(quadpy.quad(ex1, 0, 4))

produces

    IntegrationError: Tolerances (abs: 1.49e-08, rel: 1.49e-08) could not be reached with the given max_num_subintervals (= 50).

## Questions

- How do I prevent this error? I tried adding an argument called `max_num_subintervals` but that did not seem to work.
- Am I using quadpy correctly for what I am trying to do? I have begun using it since I wanted to take derivatives of complex numbers which scipy does not support, and I would like to have a one-size-fits-all solution, thus using quadpy for these easier examples that scipy would be enough.

---

## Possible Solution and further questions

After some more experimenting I have found that quadpy's quad method takes the same argument as scipys quad method, which can be found here:

- https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.quad.html#scipy.integrate.quad 

Using the `epsabs, epsrel, limit` optional arguments I can thus prevent the error:

    print(quadpy.quad(ex1, 0, 4, epsabs=1e-1, epsrel=1e-1, limit=100))

produces

    (array(7.6323447), array(0.01666253))

However scipys quad method reaches an error tolerance of `1-08`, which I really cant reproduce with quadpy, even when setting the limit to a really high value like `1000000`

Why is that?

  [1]: https://i.stack.imgur.com/XwSQr.png

**Comment by nschloe** [comment]
Cannot reproduce. This
```python
import numpy as np
from scipy.integrate import quad
import quadpy

T = 2 * np.pi


def ex1(t):
    return np.where(np.logical_and((t % T >= 0), (t % T < np.pi)), t % T, np.pi)


print(quadpy.__version__)
print(quadpy.quad(ex1, 0, 3))
print(quad(ex1, 0, 3))
```
```
0.14.6
(array(4.5), array(1.41692995e-19))
(4.5, 4.9960036108132044e-14)
```
You're probably using an outdated version.

**Comment by charelF** [comment]
I see that you have done some changes, and I can attest that the issue with a range between 0 and 3 is gone, however I sadly believe the problem is not yet quite solved.

Executing

    import numpy as np
    from scipy.integrate import quad
    import quadpy

    T = 2 * np.pi

    def ex1(t):
        return np.where(np.logical_and((t % T >= 0), (t % T < np.pi)), t % T, np.pi)

    print(quadpy.__version__)
    print(quadpy.quad(ex1, 0, 4))
    print(quad(ex1, 0, 4))

Now correctly produces:

    0.14.7
    (array(7.63156841), array(1.13827355e-16))
    (7.631568411183528, 1.0717732083155035e-08)

However a new problem has appeared:

    print(quadpy.__version__)
    print(quadpy.quad(ex1, 0, 6.28))
    print(quad(ex1, 0, 6.28))

produces

    0.14.7
    (array(14.79440093), array(2.48700624e-19))
    (14.794400932271952, 1.6431300764452317e-13)

However

    print(quadpy.__version__)
    print(quadpy.quad(ex1, 0, 6.3))
    print(quad(ex1, 0, 6.3))

throws the error again. When I then try:

    print(quadpy.__version__)
    print(quadpy.quad(ex1, 0, 6.3, epsabs=1, epsrel=1, limit=100000))
    print(quad(ex1, 0, 6.4))

I get

    0.14.7
    (array(14.85726686), array(0.22412579))
    (14.811229443894236, 1.6103077285539364e-07)

Something weird seems to be going on. The interval T used in the function is 2*pi, so 6.28..., and somehow the error goes from e-19 to 0.22 in the small interval increase 6.28 to 6.3.

I tried some more experiments, and I am really not sure whether what I'm observing is expected behaviour or not, and whether it even matters. I hope I'm not causing too much work, sorry for reopening the issue

**Comment by nschloe** [comment]
Thanks again for the good report. This led to a general improvement of quad, also fixing this issue.

**Comment by charelF** [comment]
Nice, I tried it out and I could not reproduce my issue. Thank you for fixing the bug and continuing to improve this awesome library!
