### ISSUE TITLE
Quadpy passes vector to univariate function

### ISSUE THREAD

**Issue by ctts2020** [nschloe/quadpy#262]
Hello,
Quadpy passes a vector of arguments to a univariate function, causing an error. The code is below. The argument t to function xi0 should be a scalar, while the integration routine passes it a vector.

    def intFunc(t, T, w, rho, H, nu, fwdVarCurve):
        res = fracRiccatiSolvTaylor(H + 0.5, w, T-t, 1.0, rho, nu) * xi0(t, fwdVarCurve)
    val = quadpy.quad(intFunc, 0.0, T, args=(T, w, rho, H, nu, fwdVarCurve))

**Comment by nschloe** [comment]
That's meant to be. You're supposed to evaluate those many points at once, which can give you a big speed-up as opposed to evaluating those points one by one.

**Comment by nschloe** [comment]
You can of course always just loop.

**Comment by ctts2020** [comment]
Thank you. I will edit my code.

**Comment by nschloe** [comment]
Cool. You should be able to edit it such that is works for quadpy _and_ scipy. Good luck!
