### ISSUE TITLE
Out of memory when trying to integrate a function

### ISSUE THREAD

**Issue by ctts2020** [nschloe/quadpy#303]
Hello,
I am using quadpy 0.14.11. I am getting the following error
```
 line 1997, in fracRiccatiSolvTaylor
    res = Y0 + Y1*tAlpha + Y2*(tAlpha**2) + Y3*(tAlpha**3) + Y4*(tAlpha**4) + Y5*(tAlpha**5)  + Y6*(tAlpha**6)
MemoryError: Unable to allocate 336. MiB for an array with shape (22020096,) and data type complex128
```
when I try to inetgrate a function. 
The code is below:
```python
    def hFunc(a, T, alpha, kappa, rho, nu):
        return fracRiccatiSolvTaylor(alpha, a, T, kappa,rho,nu, fwdVarForm=False)
    def intFuncG1(T, vBar, kappa, a, rho, nu, alpha):
        return vBar * kappa * hFunc(a, T, alpha, kappa, rho, nu)
    g1 = quadpy.quad(intFuncG1,0.0,T, args=(vBar, kappa, a, rho, nu, alpha), epsabs=1e-1, epsrel=1e-1, limit=100)
```
fracRiccatiSolvTaylor returns a complex number by evaluating a polynomial in t with complex coefficients. I don't want to post that as its proprietary. 
I debugged into it, somehow ~1e6 values are being generated in the integration routine and passed to fracRiccatiSolvTaylor.
Thank you.

**Comment by nschloe** [comment]
There's nothing I can do without a minimum working example.

**Comment by nschloe** [comment]
Also not that quadpy is under the GPLv3, so you cannot use it in a code that is distributed without its sources.

**Comment by ctts2020** [comment]
Hello,

I will cease using quadpy in order to avoid issues.

Regards
