### ISSUE TITLE
Integrate function of two arguments

### ISSUE THREAD

**Issue by twhughes** [nschloe/quadpy#315]
I'm interested in using quadpy to perform numerical integration of a function of two variables.

For example, integrating a function `f(x,y)` over two different triangles.

```integral integral dr dr' ( f(r, r') ) ```

Does quadpy support such an integration?

If not, are there any ways you'd recommend approaching this?
 
I've tried playing around with `functools.partial` to turn this into two separate integrals, however it seems that this doesnt work because the function argument to `integrate` needs to return an array, not a function.

Any ideas?  Thanks for your help

**Comment by nschloe** [comment]
How about one of these: https://github.com/nschloe/quadpy#triangle-t2?

**Comment by twhughes** [comment]
So I can use this to integrate an `f(x)` over one triangle.  But in my case, I need to compute some coupling between two separate triangles.  This is described by `f(x, y)` where `x` are the points within triangle 1 and `y` are the points within triangle 2.

So I'm wondering if these integration schemes can be modified to handle this case. 

Hopefully this makes sense.  Thanks for your response.

**Comment by twhughes** [comment]
something like this is what I need
```python
scheme = quadpy.t2.xiao_gimbutas_05()
triangle1 = [[0.0, 0.0], [1.0, 0.0], [0.5, 0.7]]
triangle2 = [[0.0, 1.0], [2.0, 0.0], [1.5, 1.7]]
f = lambda x, y: numpy.exp(x[0]) + numpy.square(y[1])
val = scheme.integrate(f, triangle1, triangle2)
```

**Comment by nschloe** [comment]
Do you need _some_ approximation to the value or do you want to supply error bounds?

**Comment by nschloe** [comment]
Check https://github.com/nschloe/quadpy/wiki/Adaptive-quadrature#triangles.

**Comment by twhughes** [comment]
thanks, any approximation would work but perhaps I can do it with this adaptive quadrature.  Thanks for looking into it

**Comment by nschloe** [comment]
Let me know if I can help you any further.

**Comment by twhughes** [comment]
Hi @nschloe 

In case you were interested, I came up with a working solution for integration of a function `f(r1, r2)` where `r1` and `r2` extend over the domains of two, respective triangles.  

I've pasted the code and a basic working case below if you find it useful.  Thanks again for your help.

```python
import quadpy
import numpy as np
import functools

def integrate_triangle(f, vertices):
    """ integrate function `f(r)` over vertices of triangle given by `vertices` """
    scheme = quadpy.triangle.xiao_gimbutas_05()
    return scheme.integrate(f, vertices.T)

def integrate_triangle_2(f, vertices1, vertices2):
    """ integrate `f(r1, r2)` over `r1` and `r2` in different triangles
        `vertices1` = triangle1 vertices
        `vertices2` = triangle2 vertices
    """

    def f1(pts):

        out = []
        for r1 in pts.T:
            g = functools.partial(f, r1)
            res = integrate_triangle(g, vertices2)
            out.append(res)

        return np.array(out)

    return integrate_triangle(f1, vertices1)

if __name__ == '__main__':

    """ example usage """

    def f(r1, r2):
        """ function to integrate
              needs to vectorize to r1.shape = (3,) r2.shape=(3, p)
        """
        diff = r1[:, np.newaxis] - r2
        return np.linalg.norm(diff, axis=0)

    vertices1 = np.random.random((3,3))
    vertices2 = np.random.random((3,3)) + 3

    print(integrate_triangle_2(f, vertices1, vertices2))
```
