### ISSUE TITLE
Missing schemes

### ISSUE THREAD

**Issue by drtrigon** [nschloe/quadpy#317]
I try to do a 1D integral along a line and a 2D integral over a rectangular surface. Using the examples provided on the [main page](https://github.com/nschloe/quadpy) I get:

```
import quadpy

scheme = quadpy.c1.gauss_patterson(5)
scheme.show()
```
results in: `AttributeError: module 'quadpy' has no attribute 'c1'`

and similar for the rectangular integration:

```
import quadpy

scheme = quadpy.c2.stroud_c2_7_2()
scheme.show()
```
results in: `AttributeError: module 'quadpy' has no attribute 'c2'`

Is this the same issue as https://github.com/nschloe/quadpy/issues/204 ? If this is the case, could you please release these schemes also? Or am I doing something wrong?

**Comment by nschloe** [comment]
Probably an outdated version of quadpy.

**Comment by drtrigon** [comment]
Installed using pip may be 1 or 2 weeks ago...?

How to check the version? How to install the most recent one?

**Comment by nschloe** [comment]
```
import quadpy
print(quadpy.__version__)
```

**Comment by zhucaoxiang** [comment]
@drtrigon I got the same issue when using the PyPi version, but it goes away when I try to install the GitHub version by `pip install git+https://github.com/nschloe/quadpy.git` and the version is also `0.14.11`.
```python
>>> import quadpy
>>> quadpy.__version__
'0.14.11'
>>> dir(quadpy)
['__about__', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_scipy_compat', 'c1', 'c2', 'c3', 'cn', 'e1r', 'e1r2', 'e2r', 'e2r2', 'e3r', 'e3r2', 'enr', 'enr2', 'helpers', 'p3', 'quad', 's2', 's3', 'sn', 't2', 't3', 'tn', 'tools', 'u2', 'u3', 'un', 'w3']
```

**Comment by drtrigon** [comment]
Thanks a lot to @zhucaoxiang - that was the problem!

As I had quadpy installed from PyPi already I had first to uninstall (otherwise it download, builds but does not install):
```
$ pip3 uninstall quadpy
$ pip3 install git+https://github.com/nschloe/quadpy.git
```

So the deployment to PyPi is the problem. For me this solution is good enough thus I'll close the issue. Feel free to re-open if you want to solve the deployment/PyPi problem also.

**Comment by drtrigon** [comment]
I have to re-open this issue - now the spherical coordinates are gone:

```
scheme = quadpy.sphere.lebedev_019()
scheme.show()
```
results now in: `AttributeError: module 'quadpy' has no attribute 'sphere'`

@zhucaoxiang: could you check this also, please?

**Comment by nschloe** [comment]
Just use `ipython` and <tab> your way through quadpy. You'll find `u3`.

**Comment by drtrigon** [comment]
I find `u3` but for spherical coordinates I need `sphere`, right? (as noted by you in the 2nd example in https://github.com/nschloe/quadpy#sphere-u3)

Furthermore the example given by you for the rectangular (or quadrilateral) scheme does NOT work also: https://github.com/nschloe/quadpy#quadrilateral-c2 It results in: `AttributeError: 'list' object has no attribute 'shape'`

So I do get the impression the examples are heavily outdated. If you don't care fine - I can find another solution...

**Comment by nschloe** [comment]
I'll do it when I find the time.

**Comment by nschloe** [comment]
Most README snippets are now part of the integration testing, so such hiccups should no longer occur.

**Comment by drtrigon** [comment]
Seems to work now - thanks!

**Comment by SergeiDBykov** [comment]
Hi, I have the same problem as the OP, I have 0.16.5 and cannot use lebedev scheme. And the link for the installation with git (pip install git+https://github.com/nschloe/quadpy.git) does not work 
`ERROR: Command errored out with exit status 128: git clone -q https://github.com/nschloe/quadpy.git /private/var/folders/1c/qqdm58sj5mjfk3xjz79fxzph0000gn/T/pip-req-build-gzx1rkmc Check the logs for full command output.`

How can I solve it?
