### ISSUE TITLE
fail to integrate on some special functions

### ISSUE THREAD

**Issue by husisy** [nschloe/quadpy#372]
Thanks for you great work. Recently I use quadpy package to do some projects, most times quadpy could quickly give the correct results, but sometimes it fails (no response and comsume more and more memory). Finally I find some representative examples (see below) and beg to get some help on this issue, many thanks.

a short summary (run on ubuntu-18.04 with miniconda environments, python-v3.7.7)

| integral function | integral interval | quadpy-v0.12.0 | quadpy-v0.15.2 |
| :-: | :-: | :-: | :-: |
| `f(x)=[1*x, 2*x]` | `[0,1]` | pass | pass |
| `f(x)=[0*x, 2*x]` | `[0,1]` | fail | fail |
| `f(x)=x` | `[-1,1]` | pass | fail |

the minimum working example (MWE) for quadpy-v0.15.2

```Python
# for quadpy-v0.15.2
import numpy as np
import quadpy
quadpy.c1.integrate_adaptive(lambda x: np.array([1,2]).reshape(-1,1,1)*x, [0,1]) #pass
quadpy.c1.integrate_adaptive(lambda x: np.array([0,2]).reshape(-1,1,1)*x, [0,1]) #fail
quadpy.c1.integrate_adaptive(lambda x: x, [-1,1]) #fail
```

the MWE for quadpy-v0.12.0

```Python
# for quadpy-v0.12.0
import numpy as np
import quadpy
quadpy.line_segment.integrate_adaptive(lambda x: np.array([1,2]).reshape(-1,1,1)*x, [0,1], eps=1e-5) #pass
quadpy.line_segment.integrate_adaptive(lambda x: np.array([0,2]).reshape(-1,1,1)*x, [0,1], eps=1e-5) #fail
quadpy.line_segment.integrate_adaptive(lambda x: x, [-1,1], eps=1e-5) #pass
```

the MWE for scipy.integrate

```Python
# almost equivalent scipy.integrate
import numpy as np
import scipy.integrate
scipy.integrate.quad(lambda x: 2*x, 0, 1)
scipy.integrate.quad(lambda x: 0*x, 0, 1)
scipy.integrate.quad(lambda x: x, -1, 1)
```

I also put those MWEs on the colab (could run directly on the browser) if this helps, see [link](https://colab.research.google.com/drive/1iwbx04kdH0ceLz0xWs2sCEad0YSbzBiY?usp=sharing).

Also, would you mind giving me some reference papers about the module `quadpy.c1`. I tried to work out this issue by reading the source code, but get lost in different schemes, Thanks again.

**Comment by nschloe** [comment]
Okay, I can reproduce. This
```
quadpy.c1.integrate_adaptive(lambda x: x, [-1,1]) #fail
```
is pretty shocking. :smile: I'll take a look later and add the respective tests. Thanks for the great report!
