### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by mancellin** [nschloe/quadpy#386]
Hi,

Thank you for your continuous work to improve this great package.

Recently some breaking changes (in the naming of the submodules) caused some minor issues in my code. I don't mind the breaking changes (especially for code in version 0.x), but it would be helpful to have them documented somewhere to keep my code up-to-date more easily.
Do you keep some kind of changelog? Or would you mind tagging the pull requests that are breaking?

**Comment by nschloe** [comment]
That's a valid point. I haven't kept a changelog out of "laziness" (prioritizing other work), but I realize that it is useful not only for breaking changes. I'll try to be more diligent about it.

For now, know that in all of my projects I follow semver, meaning that you can expect breaking changes if the leftmost nonzero version digit changes.

Thanks again for the suggestion.
