### ISSUE TITLE
schemes dictionary problems

### ISSUE THREAD

**Issue by keithbriggs** [nschloe/quadpy#393]
"If you would like to use a particular scheme, you can pick one from the dictionary quadpy.t2.schemes."  However,

kbriggs@Dell:~/python> python3 
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import quadpy
>>> scheme=quadpy.s3.schemes['mysovskih']
>>> scheme.integrate(lambda x: np.exp(0),[0.0,0.0,0.0],1.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute 'integrate'

**Comment by nschloe** [comment]
You need to instantiate the scheme first:
```python
scheme = quadpy.s3.schemes['mysovskih']()
```

**Comment by keithbriggs** [comment]
That's very non-obvious - it needs documenting.   Or could you have a lazy dictionary, which instantiates when looked up?

(Anyway "import quadpy" is bad as it typically imports too much.  Why not "from quadpy import s3"?)

**Comment by nschloe** [comment]
> That's very non-obvious 

I agree. If you have a good idea how to handle this, let me know.

**Comment by nschloe** [comment]
Ah, I just remembered one other hurdle: _Some_ schemes have arguments, a parameter, and those obviously _must_ be called with `(something)`. That's why I once decided to make them all callable, and to avoid the long import times.

**Comment by nschloe** [comment]
I thought about this some more and decided to keep things as they are.

Reasons:
  * A considerable number or schemes only make sense when instantiated with arguments. For example, all n-dimensional schemes need `dim`. Other schemes are really parametrized scheme families that need an `alpha`. It's consistent to have to instantiate _all_ schemes, not just some.
  * This also fixes the slow import problem.
  * Implementing a "lazy dict" would perhaps be possible, but adds more complication.

**Comment by nschloe** [comment]
If you can think of a method to work around these issues, let me know.

**Comment by keithbriggs** [comment]
ok
