### ISSUE TITLE
Wrong weight for C2 linear or constant.

### ISSUE THREAD

**Issue by Adamche1** [nschloe/quadpy#396]
Using version 0.16.4.

I believe the weights of the quad integration scheme for linear or constant (1 and 0) powers is wrong.
The point and scheme.show() suggest the domain: [-1,1]x[-1,1], for which the weight should be 4. 
Instead one finds the weight 1.
```python
scheme = quadpy.c2.get_good_scheme(1)
scheme.points
array([[0.],
       [0.]])
scheme.weights
array([1.])
```

**Comment by nschloe** [comment]
Nah it's fine, the sum of the weights is normalized to 1 for all domains. The domain volume is factored in at integration time.

**Comment by Adamche1** [comment]
Ok thanks. Sorry for the confusion.
