### ISSUE TITLE
Inconsistency in c2 integration?

### ISSUE THREAD

**Issue by fjschm** [nschloe/quadpy#401]
Thank you very much for the great package. I am very new to it, it might be that I do not have the right understanding. I am testing it for applications in a numerical PDE environment. I just look at two 2D test function supplied in **quadpy/examples_test.py** with minimal changes. The function **test_t2()** returns the expected results: the integral value on a single triangle is the same as for identically copied triangles. The function **test_c2()** has a different behavior: the integral value on a single square is just the half of the value returned for identically copied squares. The value for the single square is right. Is that okay?

Here are the two functions (quadpy 0.16.5, python 3.7):
```python
import numpy
import quadpy

def test_t2():
    val = quadpy.t2.schemes["cubtri"]().integrate(
        lambda x: numpy.exp(x[0]), numpy.array([[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]])
    )
    print('single triangle:', val)
    
    val = quadpy.t2.schemes["cubtri"]().integrate(
        lambda x: [numpy.exp(x[0]), numpy.exp(x[1])],
        numpy.stack(
            [
                [[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]],
                [[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]],
                [[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]],
                [[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]],
                [[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]],
            ],
            axis=-2,
        ),
    )
    print('multiple triangles:\n', val)
    assert val.shape == (2, 5)


def test_c2():
    val= quadpy.c2.schemes["stroud_c2_5_4"]().integrate(
        lambda x: numpy.exp(x[0]),
        quadpy.c2.rectangle_points([0.0, 1.0], [0.0, 1.0]),
    )
    print('single square:', val)

    val = quadpy.c2.schemes["stroud_c2_5_4"]().integrate(
        lambda x: [numpy.exp(x[0]), numpy.exp(x[1])],
        numpy.stack(
            [
                quadpy.c2.rectangle_points([0.0, 1.0], [0.0, 1.0]),
                quadpy.c2.rectangle_points([0.0, 1.0], [0.0, 1.0]),
                quadpy.c2.rectangle_points([0.0, 1.0], [0.0, 1.0]),
                quadpy.c2.rectangle_points([0.0, 1.0], [0.0, 1.0]),
                quadpy.c2.rectangle_points([0.0, 1.0], [0.0, 1.0]),
            ],
            axis=-2,
        ),
    )
    print('multiple squares:\n', val)
    assert val.shape == (2, 5)


test_t2()
test_c2()
```
And the result is:
**single triangle:** 0.7182818284626384
**multiple triangles:**
 [[0.71828183 0.71828183 0.71828183 0.71828183 0.71828183]
 [0.71828183 0.71828183 0.71828183 0.71828183 0.71828183]]

**single square:** 1.718281004372522
**multiple squares:**
 [[3.43656201 3.43656201 3.43656201 3.43656201 3.43656201]
 [3.43656201 3.43656201 3.43656201 3.43656201 3.43656201]]

I guess the last values should also be 1.718....
Thank you very much for any help.

**Comment by nschloe** [comment]
Thanks for the concise report! This is fixed by https://github.com/nschloe/quadpy/pull/402. WIll release 0.16.6 in a few minutes.
