### ISSUE TITLE
Python unable to import quadpy.line-segment

### ISSUE THREAD

**Issue by VivienPerrin-PhD** [nschloe/quadpy#403]
I am trying to use the adaptive integration procedure on a line segments just as in the example provided on Git. But pyhton is not able to find the line_segment package:
the code:
'import numpy as np
import quadpy

def f(x):
    return np.sin(x) - x

val, err = quadpy.line_segments.integrate_adaptive(f, [0.0, 6.0])'

Error:
'
  File "/Users/vivienperrin/Desktop/untitled0.py", line 17, in <module>
    val, err = quadpy.line_segments.integrate_adaptive(f, [0.0, 6.0])

AttributeError: module 'quadpy' has no attribute 'line_segments' '

**Comment by nschloe** [comment]
I think you're after `quadpy.c1`.

**Comment by VivienPerrin-PhD** [comment]
I am seeking for an integration algorithm which is able to sample a function with local sharpness on a rather large segment (also this function is not analytic and requires huge computing times to be computed at each points on a uniform mesh). Is it not hat the adaptive curvaature is doing?
Thanks for your help.

**Comment by nschloe** [comment]
Adaptive integration, yes.

**Comment by VivienPerrin-PhD** [comment]
So I ould need quadpy.c1.integrate_adaptive(f,[a,b]) ?
Sorry, it should seem  a really naive question...

**Comment by nschloe** [comment]
Or you use the scipy interface `quadpy.quad(f, a, b)`.

A tip: If you're unsure what a module has to offer, a good way to search through it is to use ipython and <tab>-expansion. Start ipython, `import quadpy`, type `quadpy.` and press <tab>. This will show you everything there is under `quadpy.`.
