### ISSUE TITLE
Shape of points in a t3 scheme

### ISSUE THREAD

**Issue by IgorBaratta** [nschloe/quadpy#406]
` quadpy.__version__   '0.16.6' `

It's probably a silly question, but I'm having trouble understanding the shape of quadrature points for `t3`.
What does `scheme.points` return for a `t3`?  
I would expect something with shape `(3, 81)` for the example below, but I'm apparently missing something.
For `c1` and `s2` the shape of points matches my expectation.

```python3
import quadpy

scheme = quadpy.t3.get_good_scheme(10)
print(scheme.points.shape)
# Out: (4, 81)

print(scheme.weights.shape)
# Out: (81,)

scheme = quadpy.c1.gauss_patterson(5)
print(scheme.points.shape)
#Out: (63,) 

scheme = quadpy.s2.get_good_scheme(6)
print(scheme.points.shape)
#Out: (2, 12)
```

**Comment by nschloe** [comment]
> What does scheme.points return for a t3?

All simplex schemes return barycentric coordinates.
