### ISSUE TITLE
[BUG] quadpy.t3  does not integrate Constant functions

### ISSUE THREAD

**Issue by itumekanik** [nschloe/quadpy#429]
**Describe the bug**
Hi, I was working on a FEM project and came across a problem with the tetrahedron integration. As it is clear from the following example, quadpy.t3  does not integrate Constant returns. I hope it is easy to reproduce. If not because of the versions of the dependencies it will be my pleasure to explore the versions I am using.

**To Reproduce**
```python
import quadpy

scheme = quadpy.t3.get_good_scheme(1)
def f(x):
    return x[0] / x[0]

def g(x):
    return 1

domain = [[0.0, 0.0, 0.0],
                 [1.0, 0.0, 0.0],
                 [0.0, 1.0, 0.0],
                 [0.0, 0.0, 1.0]]

valf = scheme.integrate(f, domain)  # Working fine
valg= scheme.integrate(g, domain)  # Drops error
```

![image](https://user-images.githubusercontent.com/31310412/135744023-6c3ec6c8-0486-4ba0-9981-afb2a66bf96f.png)

**Comment by nschloe** [comment]
```
def g(x):
    return [1]
```

**Comment by itumekanik** [comment]
> ```python
> def g(x):
>     return [1]
> ```
In my opinion,
It would still be better if you provide support for constants also, for a better type consistency, as x[0]/x[0] does not resolve to an array. I will definitely explore the code to see what I can offer when I have time. Great project by the way.
Best regards.

**Comment by nschloe** [comment]
> as x[0]/x[0] does not resolve to an array.

It does though.

**Comment by itumekanik** [comment]
> > as x[0]/x[0] does not resolve to an array.
> 
> It does though.

Sure it does, but implicitly. The following integrals gives exactly the same result which I believe breaks the type consistency, at least from a naive user perspective. Anyway, this is your work and I appreciate the effort.

```py
def f(x):
    return x[0] / x[0] + 1

def g(x):
    return x[0] / x[0] + [1]
```

**Comment by nschloe** [comment]
>  The following integrals gives exactly the same result which I believe breaks the type consistency, at least from a naive user perspective.

What does type consistency have to do with it? Note how
```python
import numpy as np

x = np.random.rand(10)

print(x + 1)
print(x + [1])
```
both give the same result. There's no way for quadpy to make any difference between the two.

quadpy's stance is pretty clear: For every input point, you have to return an output value.

**Comment by itumekanik** [comment]
> ```python
> import numpy as np
> 
> x = np.random.rand(10)
> 
> print(x + 1)
> print(x + [1])
> ```

I could give the same example. How about that then?
```py
import numpy as np
x = np.asarray(1)
print(x + 1)
print(x + [1])
```
Different results, probably as a result of the broadcasting.

The type consistency here, in my view, is not that technical, but it is like, trying to allow users to feel like "if both statements looks the same (not necessarily of the same type), so they should work perfectly in the same way" as is the case for "x[0]/x[0]=1".

So as an end user, I expect if "x[0]/x[0]" which looks like "1"  and works fine then "1" should also work fine in the same way. And I think there should be ways to achieve this, if not with ordinary programming but meta-programming features of python would help, i am not sure. 

Thank you. I took a lot of your time. Sorry on that.
