### ISSUE TITLE
What does this message mean?

### ISSUE THREAD

**Issue by keithbriggs** [nschloe/quadpy#443]
I got the message:

`UserWarning: Lebedev(131) (U3) has low precision (1.007e-12)`

What does "precision" mean here?   Why isn't 1e-12 high precision?

**Comment by nschloe** [comment]
It means that this particular Lebedev scheme does not integrate all polynomials of the given degree to around machine precision, but 1.0e-12. Still quite good.

**Comment by keithbriggs** [comment]
Ok, thank you.
