### ISSUE TITLE
Quadpy RuntimeError

### ISSUE THREAD

**Issue by tuabul** [nschloe/quadpy#474]
Hi, I've installed quadpy for Python 3.11.3 in Windows 10. When I try using it:
```
import numpy as np
from quadpy import quad
```
I get:
```
File "f:\IRQ\Monitorías\Codigos Python\thermodynamics.py", line 2, in <module>
    from quadpy import quad
  File "f:\IRQ\Monitorías\Codigos Python\.venv\Lib\site-packages\quadpy\__init__.py", line 1, in <module>
    from . import c1
  File "f:\IRQ\Monitorías\Codigos Python\.venv\Lib\site-packages\quadpy\c1\__init__.py", line 1, in <module>
    from .._agg import _sY7RF as integrate_adaptive, _153Er as chebyshev_gauss_1, _2p1lN as chebyshev_gauss_2, _rbReG as clenshaw_curtis, _OQgWz as fejer_1, _fknxy as fejer_2, _IzvJK as gauss_jacobi, _Wfdvf as gauss_kronrod, _62S6u as gauss_legendre, _8WSvT as gauss_lobatto, _ANIuu as gauss_patterson, _liFwk as gauss_radau, _OBFfs as midpoint, _UeKZr as newton_cotes_closed, _F8EOV as newton_cotes_open, _CItT8 as trapezoidal
  File "f:\IRQ\Monitorías\Codigos Python\.venv\Lib\site-packages\quadpy\_agg\__init__.py", line 2, in <module>
    x21.dex_23c(__file__)
RuntimeError: _x21: Could not read data file f:\IRQ\Monitorías\Codigos Python\.venv\Lib\site-packages\quadpy\_agg\__init__.dat  
```
If it helps, I'm using VScode, I would appreciate any help.

**Comment by nschloe** [comment]
That's weird. Does the file exist on your computer?

**Comment by tuabul** [comment]
Yes, it does:
![image](https://github.com/sigma-py/quadpy/assets/133028779/60428f9f-eeb5-4e4f-bacf-a4c875912f54)

**Comment by nschloe** [comment]
- Okay, first try updating all involved packages, e.g.,
  ```
  pip install quadpy x21 --force
  ```

- Second, let's check the file's shasum via
  ```
  shasum /path/to/__init__.dat
  ```

- Third, perhaps the file got installed with insufficient permissions?

**Comment by tuabul** [comment]
I tried with `--force` and got the same message. And how can I use the `shasum`? is it a library?
And what type of permissions do I need to give? :(

**Comment by tuabul** [comment]
Another thing, if I make other .venv in other folder, the message is this:
```
Error: Unable to find valid license for Sigma. 

Add a license with

    plm add <your-license-key>
```

**Comment by nschloe** [comment]
You can have the shasum computed from any online source, or the command line. It's just there to make sure the file contents are correct.

> Another thing, if I make other .venv in other folder, the message is this:

That's right! Perhaps your other venv installation is broken in some way?

**Comment by nschloe** [comment]
Closing for now. Let me know if you have any more issues!
