### ISSUE TITLE
Adaptive multivariate integration over hypercubes

### ISSUE THREAD

**Issue by HJA24** [nschloe/quadpy#475]
Hi,

Is it possible to use `quadpy` for adaptive multivariate integration over hypercubes? I am currently using this R-[function](https://www.rdocumentation.org/packages/cubature/versions/1.0/topics/adaptIntegrate), but ideally would like to keep everything in a Python-environment.
If possible, could you provide some sample code? I cannot find any examples regarding hypercubes in the documentation.

Thank you!

**Comment by nschloe** [comment]
That's not implemented yet, no. Would you be interested in that feature?

**Comment by HJA24** [comment]
100%!

**Comment by nschloe** [comment]
Give me some details. What's the dimensionality? What does the function look like? etc.

**Comment by HJA24** [comment]
I am rewriting the R-code in the Appendex of this [paper](https://www.degruyter.com/document/doi/10.1515/jqas-2017-0122/html?lang=en)


```python
import scipy.stats as ss

def G(f, x, n, theta, a, b, c1, c2, k):

    def l_3_1(p, theta):
        if p > (1 / theta):
            kelly = (p * theta - 1) / (theta - 1)
        else:
            kelly = 0

        if p < (f * (theta - 1) + 1) / theta:
            loss_func = (c1 + c2) * (abs(f - kelly) ** k)
        else:
            loss_func = 0

        return loss_func * ss.beta.pdf(p, a + x, n - x + b)

    def l_3_2(p, theta):
        if p > (1 / theta):
            kelly = (p * theta - 1) / (theta - 1)
        else:
            kelly = 0

        if p >= (f * (theta - 1) + 1) / theta:
            loss_func = c2 * (abs(f - kelly) ** k)
        else:
            loss_func = 0

        return loss_func * ss.beta.pdf(p, a + x, n - x + b)

    # integrate the loss functions
    part_1 = quadpy.relevantFunction(l_3_1,
                                     lowerLimit=0,
                                     upperLimit=(f * (theta - 1) + 1) / theta,
                                     tol=1e-10)
    part_2 = quadpy.relevantFunction(l_3_2,
                                     lowerLimit=(f * (theta - 1) + 1) / theta,
                                     upperLimit=1,
                                     tol=1e-10)
 
    # return the sum of the two integrals
    return part_1 + part_2
```

What do you think?

**Comment by nschloe** [comment]
Those integrals are just one-dimensional, right?

**Comment by HJA24** [comment]
You're right. Excuse my ignorance, but which `quadpy` function would you use for this then?

**Comment by nschloe** [comment]
`quadpy.quad`

https://github.com/sigma-py/quadpy#using-quadpy

More things are a little weird about the implementation, but perhaps you'll be able figure it out by yourself.

**Comment by HJA24** [comment]
I understand your point and altered my script. 
Can you show me how to use `quadpy.quad` to integrate over multiple limits? I created a separate Stackoverflow-[question](https://stackoverflow.com/questions/76472773/integrate-over-multiple-limits-at-once-using-quadpy) as this topic can be closed.

**Comment by nschloe** [comment]
If you need any more help with this, note that Sigma licenses come with proritized bug fixing. Just let us know your license e-mail address and we'll tackle the issue.

**Comment by HJA24** [comment]
Help would be welcome (hjmeulenbelt@gmail.com). I closed this topic and opened a new [one](https://github.com/sigma-py/quadpy/issues/476) as the script / problem changed
