### ISSUE TITLE
Integrate over multiple limits at once using Quadpy

### ISSUE THREAD

**Issue by HJA24** [nschloe/quadpy#476]
Hi,

I would love some help with integration over multiple limits at once. I am not sure which function I should use for this matter. 
I created the following Stackoverflow-[topic](https://stackoverflow.com/questions/76472773/integrate-over-multiple-limits-at-once-using-quadpy/76494602#76494602) (with 50 points as bounty). However no luck so far and as the software is licensed, I expect higher likelihood of success here.

My script looks as follows:

```python
import quadpy
import numpy as np


class Kelly:
    def __init__(self):
        self.odds = 1.952
        self.kelly = 0.08961344537815132
        self.i = 0.001
        self.f = np.arange(0, 1 + self.i, self.i).flatten()
        self.c1 = 1
        self.c2 = 2
        self.k = 1.5

    def loss_function(self, p):
        p = p[:, 0]
        loss_function = np.where(np.less(p[:, None], (self.f * self.odds - 1) + 1 / self.odds),
                                (self.c1 + self.c2) * abs(self.f - self.kelly) ** self.k, 
                                 0)
        return loss_function

    def integrate(self):
        xmin = np.zeros(len(self.f))
        xmax = np.array([self.f * (self.odds - 1) + 1 / self.odds]).flatten()

        vals, errors = quadpy.c1.integrate_adaptive(lambda x: self.loss_function, xmin, xmax)

        return vals, errors


kelly = Kelly()
vals, errors = kelly.integrate()
print(vals, errors)

```

This results in the following error:

>   File "/Users/User/PycharmProjects/exchanges/kelly/test.py", line 25, in integrate
>     vals, errors = quadpy.c1.integrate_adaptive(lambda x: self.loss_function(x), xmin, xmax)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<string>", line 4, in wrapper
>   File "<string>", line 4835, in _sY7RF
> AssertionError

Please advice what I should be change. 

Expected output of `vals`

`[0.         0.         0.         ... 1.3305999  1.3327977  1.33499671]`

This is the output of the following script

```
from cubature import cubature
import numpy as np


class Kelly:
    def __init__(self):
        self.odds = 1.952
        self.kelly = 0.08961344537815132
        self.i = 0.001
        self.f = np.arange(0, 1 + self.i, self.i).flatten()
        self.c1 = 1
        self.c2 = 2
        self.k = 1.5

    def loss_function(self, p):
        p = p[:, 0]
        loss_function = np.where(np.less(p[:, None], (self.f * self.odds - 1) + 1 / self.odds),
                                (self.c1 + self.c2) * abs(self.f - self.kelly) ** self.k, 
                                 0)
        return loss_function

    def integrate_vec(self):
        xmin = np.zeros(len(self.f))
        xmax = np.array([self.f * (self.odds - 1) + 1 / self.odds]).flatten()
        vals, errors = cubature(func=self.loss_function,
                                ndim=1,
                                fdim=len(self.f),
                                xmin=xmin,
                                xmax=xmax,
                                vectorized=True)
        return vals, errors


kelly = Kelly()
vals, errors = kelly.integrate_vec()
print(vals, errors)
```

The goal is to compare the speed of the two different scripts.

**Comment by maciejskorski** [comment]
I would blame the function signature. Answered in your original question on SO.

**Comment by nschloe** [comment]
Your `loss_function` is a bit weird: Whenever `p` is less than a given value, the return value is an array, otherwise it's `0`. That doesn't make sense. If your function really is 0-or-1, Gaussian integration isn't well suited to the problem either.

Also, you probably mean to use `quadpy.quad` instead of `quadpy.c1.integrate_adaptive`.

I'll release a new quadpy version shortly which will feature better error messages.

**Comment by HJA24** [comment]
Thanks for checking. The loss function works for the `cubature`-version. How can I rewrite it in such a way it also works for `quadpy`?

**Comment by maciejskorski** [comment]
The function is missing a signature: what is the input shape and what is the output shape?

**Comment by nschloe** [comment]
> Thanks for checking. The loss function works for the `cubature`-version. How can I rewrite it in such a way it also works for `quadpy`?

Let's see the working variant.

**Comment by HJA24** [comment]
> > Thanks for checking. The loss function works for the `cubature`-version. How can I rewrite it in such a way it also works for `quadpy`?
> 
> Let's see the working variant.

The code can be found in the first post of this topic. Here it is

```python
from cubature import cubature
import numpy as np


class Kelly:
    def __init__(self):
        self.odds = 1.952
        self.kelly = 0.08961344537815132
        self.i = 0.001
        self.f = np.arange(0, 1 + self.i, self.i).flatten()
        self.c1 = 1
        self.c2 = 2
        self.k = 1.5

    def loss_function(self, p):
        p = p[:, 0]
        loss_function = np.where(np.less(p[:, None], (self.f * self.odds - 1) + 1 / self.odds),
                                (self.c1 + self.c2) * abs(self.f - self.kelly) ** self.k, 
                                 0)
        return loss_function

    def integrate_vec(self):
        xmin = np.zeros(len(self.f))
        xmax = np.array([self.f * (self.odds - 1) + 1 / self.odds]).flatten()
        vals, errors = cubature(func=self.loss_function,
                                ndim=1,
                                fdim=len(self.f),
                                xmin=xmin,
                                xmax=xmax,
                                vectorized=True)
        return vals, errors


kelly = Kelly()
vals, errors = kelly.integrate_vec()
print(vals)
# [0.         0.         0.         ... 1.3305999  1.3327977  1.33499671]
```

**Comment by HJA24** [comment]
> The function is missing a signature: what is the input shape and what is the output shape?

The input- and output shape are equal to `(1, len(self.f))`

**Comment by nschloe** [comment]
I just spent some time looking at the functions and it's not entirely clear to me what you're trying to do mathematically. Your `loss_function` gets a vector of shape `(n,)`, and returns an array of shape `(n, 1001)`. Those are the characteristics of a vector-valued function on a 1D interval. Is this correct?

I've also improved the error messages; they should be more helpful for your use case now.
