### ISSUE TITLE
License Key Requirement for Quadpy Library

### ISSUE THREAD

**Issue by iitt-piyush** [nschloe/quadpy#481]
Hello,

I recently attempted to use the quadpy library for numerical integration over triangular domains. However, I encountered a message indicating that a valid license key is required:
Warning: Unable to find valid license for product ID 06b7db1d-5a40-4d2c-b89c-6b1887c377c1.
Enter license key:
I am unsure about how to obtain this license key. I have a few questions:

Is quadpy now requiring a license key for usage?
If so, how can I obtain a license key for the library?
Are there any specific steps or procedures to follow to resolve this issue?
I would appreciate any guidance or information you can provide on this matter. Thank you for your assistance.

Best regards,
Piyush Gupta

**Comment by nschloe** [comment]
Hi Piyush, see [here](https://github.com/sigma-py/) for more info.
