### ISSUE TITLE
sphere: integrate functions defined by theta, phi

### ISSUE THREAD

**Issue by nschloe** [nschloe/quadpy#70]
To this end, transform the coordinates of the quadrature schemes to theta, phi.

**Comment by tokotchd** [comment]
Fastest way I've seen this done is via:

r = (x**2 + y**2 +z**2)**0.5
#theta = np.arctan2(z, (x**2+y**2)**0.5) 
theta = np.arccos(z/r)
phi = np.arctan2(y,x)

**Comment by nschloe** [comment]
Thanks for the hint.

I'm guessing that the quadrature points are much simpler in spherical coordinates than what's in the code now. We'll have to see.

**Comment by nschloe** [comment]
There's now
```python
val = quadpy.sphere.integrate_spherical(
    lambda phi_theta: numpy.sin(phi_theta[0])**2 * numpy.sin(phi_theta[1]),
    radius=1.0,
    rule=quadpy.sphere.Lebedev(19)
    )
```
